name: 🚀 Publish to PyPI
permissions:
  contents: read

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install Poetry
        uses: knowsuchagency/poetry-install@v2
        with:
          create-virtualenv: false    # install Poetry globally so JRubics/poetry-publish can find it

      - name: Build and publish to PyPI
        uses: JRubics/poetry-publish@v1.13
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
