# .github/workflows/test.yml
name: 🧪 Test
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # 1) Checkout your code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2) Set up Python & cache Poetry’s download cache
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          

      # 3) Install Poetry (so `poetry` is on the PATH)
      - name: Install Poetry
        run: pip install poetry

      # 4) Install *all* dependencies (runtime + dev)
      #    Since you’re using a [tool.poetry.group.dev.dependencies] section,
      #    add `--with dev` so pytest & coverage get installed.
      - name: Install dependencies
        run: poetry install --with dev

      # 5) Run your real tests
      - name: Run pytest
        run: |
          poetry run pytest --maxfail=1 --disable-warnings -q
